version: '3'
services:
  zookeeper-1:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    restart: unless-stopped
    volumes:
      - ./zookeeper/data:/data
      - ./zookeeper/datalog:/datalog
    networks:
      my-network:
        ipv4_address: 172.18.0.100
  zookeeper-2:
    image: wurstmeister/zookeeper
    ports:
      - "2182:2181"
    restart: unless-stopped
    volumes:
      - ./zookeeper/data:/data
      - ./zookeeper/datalog:/datalog
    networks:
      my-network:
        ipv4_address: 172.18.0.101
  zookeeper-3:
    image: wurstmeister/zookeeper
    ports:
      - "2183:2181"
    restart: unless-stopped
    volumes:
      - ./zookeeper/data:/data
      - ./zookeeper/datalog:/datalog
    networks:
      my-network:
        ipv4_address: 172.18.0.102

  kafka-1:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 172.18.0.103
      KAFKA_CREATE_TOPICS: "test:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181, zookeeper-2:2182, zookeeper-3:2183
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    depends_on:
      - zookeeper-1
    networks:
      my-network:
        ipv4_address: 172.18.0.103
  kafka-2:
    image: wurstmeister/kafka
    ports:
      - "9093:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 172.18.0.104
      KAFKA_CREATE_TOPICS: "test:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181, zookeeper-2:2182, zookeeper-3:2183
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    depends_on:
      - zookeeper-2
    networks:
      my-network:
        ipv4_address: 172.18.0.104
  kafka-3:
    image: wurstmeister/kafka
    ports:
      - "9094:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 172.18.0.105
      KAFKA_CREATE_TOPICS: "test:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181, zookeeper-2:2182, zookeeper-3:2183
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    depends_on:
      - zookeeper-3
    networks:
      my-network:
        ipv4_address: 172.18.0.105
  
networks:
  my-network:
    name: food-express-network
    external: true